# Example Wikibase docker-compose setup
version: '3.4'

x-common-variables: &wikibase_variables
  DB_SERVER: mysql.svc:3306
  MW_ADMIN_NAME: ${MW_ADMIN_NAME}
  MW_ADMIN_PASS: ${MW_ADMIN_PASS}
  MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
  MW_WG_SECRET_KEY: ${MW_SECRET_KEY}
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_NAME: ${DB_NAME}

services:
  wikibase:
    image: wikibase/wikibase-bundle:1.35.4-wmde.2
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - quickstatements-data:/quickstatements/data
    networks:
      default:
        aliases:
         - wikibase-docker.svc
    environment:
      <<: *wikibase_variables

  mysql:
    image: mariadb:10.3
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc
         
  quickstatements:
    image: ghcr.io/mardi4nfdi/docker-quickstatements:master
    container_name: mardi-quickstatements
    restart: unless-stopped
    volumes:
      - quickstatements-data:/quickstatements/data
    ports:
      - "8841:80"
    depends_on:
      - wikibase
    networks:
      default:
        aliases:
         - quickstatements.svc
    environment:
      - QUICKSTATEMENTS_HOST
      - WIKIBASE_SCHEME_AND_HOST=http://wikibase-docker.svc
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://${QUICKSTATEMENTS_HOST}:${QUICKSTATEMENTS_PORT}
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://${WIKIBASE_HOST}:${WIKIBASE_PORT}
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
      - OAUTH_CONSUMER_KEY=${OAUTH_CONSUMER_KEY}
      - OAUTH_CONSUMER_SECRET=${OAUTH_CONSUMER_SECRET}

  selenium:
    image: aot29/selenium
    container_name: qs-test-selenium
    volumes:
      - ./test:/test

volumes:
  #shared:
  mediawiki-mysql-data:
  quickstatements-data:
