# Example Wikibase docker-compose setup
version: '3.4'

x-common-variables: &wikibase_variables
  DB_SERVER: mysql.svc:3306
  MW_ADMIN_NAME: ${MW_ADMIN_NAME:-admin}
  MW_ADMIN_PASS: ${MW_ADMIN_PASS:-vRhw9zTMbM6Sq8Af}
  MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL:-e@ma.il}
  MW_WG_SECRET_KEY: ${MW_SECRET_KEY:-secret}
  DB_USER: ${DB_USER:-dbuser}
  DB_PASS: ${DB_PASS:-dbpass}
  DB_NAME: ${DB_NAME:-dbname}
  QS_PUBLIC_SCHEME_HOST_AND_PORT: http://localhost:8841
  
services:
  wikibase:
    image: wikibase/wikibase-bundle:1.35.4-wmde.2
    container_name: qs-test-wikibase
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ../mediawiki/Quickstatements.sh:/Quickstatements.sh
      - ../mediawiki/LocalSettings.override.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
      - quickstatements-data:/quickstatements/data
    networks:
      default:
        aliases:
         - wikibase-docker.svc
    environment:
      <<: *wikibase_variables

  mysql:
    image: mariadb:10.3
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: ${DB_NAME:-dbname}
      MYSQL_USER: ${DB_USER:-dbuser}
      MYSQL_PASSWORD: ${DB_PASS:-dbpass}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc
         
  quickstatements:
    image: ghcr.io/mardi4nfdi/docker-quickstatements:master
    container_name: qs-test-quickstatements
    volumes:
      - ../quickstatements/public_html:/var/www/html/quickstatements/public_html
      - ../magnustools:/var/www/html/magnustools
      - quickstatements-data:/quickstatements/data
    ports:
      - "8841:80"
    depends_on:
      - wikibase
    networks:
      default:
        aliases:
         - quickstatements.svc
    environment:
      - WIKIBASE_SCHEME_AND_HOST=http://wikibase-docker.svc
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:8841
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:8081
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
      - OAUTH_CONSUMER_KEY=${OAUTH_CONSUMER_KEY}
      - OAUTH_CONSUMER_SECRET=${OAUTH_CONSUMER_SECRET}

  selenium:
    image: aot29/selenium
    container_name: qs-test-selenium
    volumes:
      - ./test:/test

volumes:
  mediawiki-mysql-data:
  quickstatements-data:
