name: docker-quickstatements-actions-workflow
on: 
  push:
    branches: 
      - 'master'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - 
        name: Build
        run: docker build -t mardi/quickstatements .

